name: Slack Notifications for push and new PR

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main

jobs:
  slack_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack Notification for Pull Request
        if: ${{ github.event_name == 'pull_request' }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{
            "text": "New pull request submitted: ${{ github.event.pull_request.html_url }} by ${{ github.event.pull_request.user.login }}"
          }' $SLACK_WEBHOOK_URL

  slack_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Send Slack Notification On Push
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        MESSAGE="${{github.event.sender.login}} has just made a new push to ${{github.repository}}. Reference #: ${{github.event.after}}.
                  Commit sha: ${{github.sha}}. More details: ${{github.event.commits}}"
        SLACK_MESSAGE="{\"text\":\"$MESSAGE\"}"
        curl -X POST -H 'Content-type: application/json' --data "$SLACK_MESSAGE" $SLACK_WEBHOOK_URL
